// Zoomed region and district maps, generated by tools/area_maps.py (© ČÚZK, CC BY 4.0).
import data from './areas.json';

interface Frame { x0: number; y0: number; z: number; pad: number; viewBox: string }
export interface DistrictArea { name: string; slug: string; label: string; d: string; lx: number; ly: number }
export interface RegionDetail extends Frame { name: string; okresy: DistrictArea[] }
export interface DistrictDetail extends Frame { name: string; kraj: string; d: string }

const { proj } = data;
const kraje = data.kraje as Record<string, RegionDetail>;
const okresy = data.okresy as Record<string, DistrictDetail>;

export const regionDetail = (slug: string): RegionDetail | undefined => kraje[slug];
export const districtDetail = (slug: string): DistrictDetail | undefined => okresy[slug];
export const districtsOf = (krajSlug: string) =>
  Object.entries(okresy).filter(([, o]) => o.kraj === krajSlug).map(([slug, o]) => ({ slug, ...o }));

/** GPS → position on a zoomed map (same projection the outlines were drawn with). */
export function toMap(f: Frame, lat: number, lng: number): [number, number] {
  const x = (lng - proj.lon0) * proj.k * proj.scale;
  const y = (proj.lat1 - lat) * proj.scale;
  return [(x - f.x0) * f.z + f.pad, (y - f.y0) * f.z + f.pad];
}
